# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Signal Processing and Learning for Wearables
author: Peter H Charlton
copyright: "2023"
logo: icon.png
exclude_patterns: [README.md]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: bsp-book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/peterhcharlton/bsp-book  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
  path_to_book: content

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

# Add launch buttons
# See https://jupyterbook.org/en/stable/interactive/launchbuttons.html
launch_buttons:
# Google Colab links will only work for pages that have the .ipynb extension.
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"
